# Test for cmake build system
name: CMake
on: [push, pull_request]
jobs:
  lz4-build-cmake:
    name: cmake, build-cmake.yml
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # https://github.com/actions/checkout

    - name: Environment info
      run: |
        echo && type cmake && which cmake && cmake --version
        echo && type make && which make && make -v

    - name: cmake
      run: |
        cd build/cmake
        mkdir build
        cd build
        cmake ..
        CFLAGS=-Werror make VERBOSE=1


  lz4-make-cmake:
    name: make cmake, build-cmake.yml
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # https://github.com/actions/checkout
    - name: make cmake
      run: |
        # V=1 for lz4 Makefile, VERBOSE=1 for cmake Makefile.
        make V=1 VERBOSE=1 clean cmake
