# Name of the workflow is also displayed as a SVG badge
name: C Compilers

on: [push, pull_request]

jobs:
  # Test various C compilers
  #
  lz4-c-compilers:
    name: $CC=${{ matrix.cc }}, ${{ matrix.os }}, c-compilers.yml
    strategy:
      fail-fast: false  # 'false' means Don't stop matrix workflows even if some matrix failed.
      matrix:
        include: [
          # You can access the following values via ${{ matrix.??? }}
          #   name : Label name.
          #   pkgs : apt-get package names.  You can include multiple package names which are delimited by space.
          #   cc   : C compiler executable.
          #   cxx  : C++ compiler executable for `make ctocpptest`.
          #   stdc90 : 'yes' if compiler supports C90 standard.
          #   stdc11 : 'yes' if compiler supports C11 standard.
          #   m32  : contains 'yes' if compiler supports x32.
          #   os   : GitHub Actions YAML workflow label.  See https://github.com/actions/virtual-environments#available-environments

          # Default C compilers
          #  We always use 'ubuntu-latest' for default C/C++ compilers.
          ####{ pkgs: '',                cc: cc,        cxx: c++,         stdc11: yes,  stdc90: yes,  stdc89: yes,  x32: yes, os: ubuntu-latest, },
          ####{ pkgs: '',                cc: gcc,       cxx: g++,         stdc11: yes,  stdc90: yes,  stdc89: yes,  x32: yes, os: ubuntu-latest, },
          { pkgs: '',                cc: clang,     cxx: clang++,     stdc11: yes,  stdc90: yes,  stdc89: yes,  x32: yes, os: ubuntu-latest, },


          # gcc
          { pkgs: 'gcc-11 lib32gcc-11-dev libx32gcc-11-dev',            cc: gcc-11,    cxx: g++-11,      stdc11: yes,  stdc90: yes,  x32: yes, os: ubuntu-20.04,  },
####          { pkgs: 'gcc-10 lib32gcc-10-dev libx32gcc-10-dev',            cc: gcc-10,    cxx: g++-10,      stdc11: yes,  stdc90: yes,  x32: yes, os: ubuntu-20.04,  },
####          { pkgs: 'gcc-9 lib32gcc-9-dev libx32gcc-9-dev',               cc: gcc-9,     cxx: g++-9,       stdc11: yes,  stdc90: yes,  x32: yes, os: ubuntu-20.04,  },
####          { pkgs: 'gcc-8 g++-8 lib32gcc-8-dev libx32gcc-8-dev',         cc: gcc-8,     cxx: g++-8,       stdc11: yes,  stdc90: yes,  x32: yes, os: ubuntu-20.04,  },
####          { pkgs: 'gcc-7 g++-7 lib32gcc-7-dev libx32gcc-7-dev',         cc: gcc-7,     cxx: g++-7,       stdc11: yes,  stdc90: yes,  x32: yes, os: ubuntu-20.04,  },
####
####          # gcc, ubuntu-18.04
####          { pkgs: 'gcc-6 g++-6 lib32gcc-6-dev libx32gcc-6-dev',         cc: gcc-6,     cxx: g++-6,       stdc11: yes,  stdc90: yes,  x32: yes, os: ubuntu-18.04,  },
####          { pkgs: 'gcc-5 g++-5 lib32gcc-5-dev libx32gcc-5-dev',         cc: gcc-5,     cxx: g++-5,       stdc11: yes,  stdc90: yes,  x32: yes, os: ubuntu-18.04,  },
####          { pkgs: 'gcc-4.8 g++-4.8 lib32gcc-4.8-dev libx32gcc-4.8-dev', cc: gcc-4.8,   cxx: g++-4.8,     stdc11: yes,  stdc90: yes,  x32: yes, os: ubuntu-18.04,  },
####
####          # gcc, ubuntu-16.04 will be removed.  See "Maintenance Schedule" at the top of this file.
####          { pkgs: 'gcc-4.7 g++-4.7 lib32gcc-4.7-dev',                   cc: gcc-4.7,   cxx: g++-4.7,     stdc11: yes,  stdc90: yes,  x32: no,  os: ubuntu-16.04,  },
          { pkgs: 'gcc-4.6 g++-4.6 gcc-4.6-multilib',                   cc: gcc-4.6,   cxx: g++-4.6,     stdc11: no,   stdc90: yes,  x32: no,  os: ubuntu-16.04,  },
          #{pkgs: 'gcc-4.5 g++-4.5',                                    cc: gcc-4.5,   cxx: g++-4.5,     stdc11: no,   stdc90: yes,  x32: no,  os: ubuntu-16.04,  },  # Failed to install gcc-4.5.  Dependent package is not installable.
          { pkgs: 'gcc-4.4 g++-4.4 gcc-4.4-multilib',                   cc: gcc-4.4,   cxx: g++-4.4,     stdc11: no,   stdc90: no,   x32: no,  os: ubuntu-16.04,  },  # gcc-4.4 doesn't support C90 https://gcc.gnu.org/onlinedocs/gcc-4.4.7/gcc/C-Dialect-Options.html#C-Dialect-Options


####          # clang
####          { pkgs: 'clang-12',  cc: clang-12,  cxx: clang++-12,  stdc11: yes,  stdc90: yes,  x32: yes, os: ubuntu-20.04,  },
####          { pkgs: 'clang-11',  cc: clang-11,  cxx: clang++-11,  stdc11: yes,  stdc90: yes,  x32: yes, os: ubuntu-20.04,  },
          { pkgs: 'clang-10 lib32gcc-10-dev libx32gcc-10-dev',  cc: clang-10,  cxx: clang++-10,  stdc11: yes,  stdc90: yes,  x32: yes, os: ubuntu-20.04,  },
####          { pkgs: 'clang-9  lib32gcc-9-dev  libx32gcc-9-dev',   cc: clang-9,   cxx: clang++-9,   stdc11: yes,  stdc90: yes,  x32: yes, os: ubuntu-20.04,  },
####          { pkgs: 'clang-8  lib32gcc-8-dev  libx32gcc-8-dev',   cc: clang-8,   cxx: clang++-8,   stdc11: yes,  stdc90: yes,  x32: yes, os: ubuntu-20.04,  },
####          { pkgs: 'clang-7  lib32gcc-7-dev  libx32gcc-7-dev',   cc: clang-7,   cxx: clang++-7,   stdc11: yes,  stdc90: yes,  x32: yes, os: ubuntu-20.04,  },
####          { pkgs: 'clang-6.0  lib32gcc-6-dev libx32gcc-6-dev', cc: clang-6.0, cxx: clang++-6.0, stdc11: yes,  stdc90: yes,  x32: yes, os: ubuntu-20.04,  },
####          { pkgs: 'clang-5.0  lib32gcc-5-dev libx32gcc-5-dev', cc: clang-5.0, cxx: clang++-5.0, stdc11: yes,  stdc90: yes,  x32: yes, os: ubuntu-18.04,  },
####          { pkgs: 'clang-4.0', cc: clang-4.0, cxx: clang++-4.0, stdc11: yes,  stdc90: yes,  x32: yes, os: ubuntu-18.04,  },
####          { pkgs: 'clang-3.9', cc: clang-3.9, cxx: clang++-3.9, stdc11: yes,  stdc90: yes,  x32: yes, os: ubuntu-18.04,  },
####          { pkgs: 'clang-3.8', cc: clang-3.8, cxx: clang++-3.8, stdc11: yes,  stdc90: yes,  x32: yes, os: ubuntu-16.04,  },
####          { pkgs: 'clang-3.7', cc: clang-3.7, cxx: clang++-3.7, stdc11: yes,  stdc90: yes,  x32: no,  os: ubuntu-16.04,  },  # clang-3.7 clashes for x32
####          { pkgs: 'clang-3.6', cc: clang-3.6, cxx: clang++-3.6, stdc11: yes,  stdc90: yes,  x32: no,  os: ubuntu-16.04,  },  # clang-3.6 clashes for x32
####          { pkgs: 'clang-3.5', cc: clang-3.5, cxx: clang++-3.5, stdc11: yes,  stdc90: yes,  x32: no,  os: ubuntu-16.04,  },  # clang-3.5 clashes for x32
        ]

    runs-on: ${{ matrix.os }}
    env:                        # Set environment variables
      # We globally set CC and CXX to improve compatibility with .travis.yml
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
    steps:
    - uses: actions/checkout@v2 # https://github.com/actions/checkout
    - name: apt-get install
      run: |
        sudo apt-get install gcc-multilib
        sudo apt-get install ${{ matrix.pkgs }}

    - name: Environment info
      run: |
        echo && which $CC
        echo && $CC --version
        echo && which $CXX
        echo && $CXX --version

    - name: make
      run: |
        make V=1

    - name: make all
      run: |
        make V=1 clean all

    - name: make c_standards (C90)
      run: |
      if: ${{ matrix.stdc90 == 'yes' }}
        make V=1 clean c_standards_c90

    - name: make c_standards (C11)
      run: |
      if: ${{ matrix.stdc11 == 'yes' }}
        make V=1 clean c_standards_c11

    - name: make c-to-c++
      run: |
        make V=1 clean ctocpptest

    - name: make cxxtest
      run: |
        make V=1 clean cxxtest

    - name: make -C programs default
      run: |
        make V=1 -C programs clean default

    - name: make -C programs default -D_FORTIFY_SOURCE=2
      run: |
        CFLAGS='-fPIC' LDFLAGS='-pie -fPIE -D_FORTIFY_SOURCE=2' make V=1 -C programs clean default

    - name: make -C tests test-lz4
      run: |
        MOREFLAGS='-Werror' make V=1 -C tests clean test-lz4

    - name: make clangtest (clang only)
      if: ${{ startsWith( matrix.cc , 'clang' ) }}
      run: |
        make V=1 clean clangtest

    - name: make -C tests test MOREFLAGS='-mx32'
      if: ${{ startsWith( matrix.x32 , 'yes' ) }}
      run: |
        MOREFLAGS='-mx32 -Wl,--verbose' make V=1 -C tests clean test

    - name: make -C tests test-lz4c32
      run: |
        MOREFLAGS='-Werror -Wl,--verbose' make V=1 -C tests clean test-lz4c32
