name: lz4 CI

on: [push, pull_request]

jobs:
  windows-msvc:
    name: windows msvc
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: build
      run: |
        pushd .\build\VS2017
        cmd.exe /c .lz4-msbuild.bat .lz4.sln /p:PlatformToolset=v142 /p:Platform=Win32 /p:Configuration=Release /p:WindowsTargetPlatformVersion=10
        popd
