name: valgrind
on: [push, pull_request]
jobs:
  lz4-valgrind:
    name: valgrind, tests-valgrind.yml
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # https://github.com/actions/checkout
    - name: apt-get install
      run: |
        sudo apt-get install valgrind

    - name: Environment info
      run: |
        echo && type cc && which cc && cc --version
        echo && type valgrind && which valgrind && valgrind --version

    - name: valgrind
      run: |
        make V=1 -C tests test-mem
